### ISSUE TITLE
Yomitan icon constantly reports errors when Anki is not enabled

### ISSUE THREAD

**Issue by stephenmk** [themoeway/yomitan#844] opened 2024-04-20 02:01 UTC
**Description**
The Yomitan icon in my browser is constantly reporting errors (the red !! icon) when Anki is not enabled.

Steps to reproduce:
1. Install Yomitan
2. Import a dictionary
3. Do not enable Anki integration
4. Perform a Yomitan search for a word

**Browser version**
I'm seeing this error in both Firefox and Chromium.

**Yomitan version**
24.4.16.0, 24.4.18.0, possibly others as well.

![errors](https://github.com/themoeway/yomitan/assets/8003332/5f161fce-c4ec-494d-92e0-01ed62582945)

**Comment by Kuuuube** [comment] 2024-04-20 02:06
Duplicate of #825 should be fixed by #843

**Closed by Kuuuube** 2024-04-20 02:06 UTC
Labels: kind/bug

**Comment by stephenmk** [comment] 2024-04-20 02:10
Oops, sorry. Nice work though. Thanks for the quick reply.
