### ISSUE TITLE
Track/Save how many times you've scanned a word / phrase / expression

### ISSUE THREAD

**Issue by aramrw** [themoeway/yomitan#1041] opened 2024-06-08 09:57 UTC
### Benefits: 
- Shows leeches at the top
  - You can forget which words are more important than others, me personally I just randomly paste them into a file in no specific order
  - Then because they are random, I have to go back through them and check their frequencies as some words are _too_ rare
- Can serve as notes
  - No longer have to break immersion to write them somewhere
 
### Features?
- Multi-select specific expressions (from the saved list), so it can be fed into `Generate Anki Notes`
- Allow sorting by frequency 
- Also maybe allow sorting by URL, and months, days, or hours?

Not expected, I'm just throwing it out there 🤷🏼‍♂️

**Comment by Kuuuube** [comment] 2024-06-08 11:54
Duplicate of #741

This is beyond the scope of yomitan and not something we want to maintain.

I agree this could be cool to have but it adds more pain than it's worth on the development side of things.

**Closed by Kuuuube** 2024-06-08 11:54 UTC
Labels: kind/enhancement
