### ISSUE TITLE
Anki not connected error displaying even when anki not enabled

### ISSUE THREAD

**Issue by andrewsartor** [themoeway/yomitan#846] opened 2024-04-20 10:06 UTC
Rel to #825, Yomitan spits out errors about anki not being integrated even when anki connection isn't enabled. 

>               I also have Anki integration disabled and am getting this error in Firefox.  It seems to have been introduced by https://github.com/themoeway/yomitan/commit/ef4304979db6a7e08b3dae1eca7e614a0ef30f1a
> I don't really understand the codebase, but I tried to find the issue and it looks like Anki integration is enabled by event listeners spawned from this:
> https://github.com/themoeway/yomitan/blob/69b57e5efdc8a25025606569f8f20ea508a5263d/ext/js/display/popup-main.js#L41-L42
> https://github.com/themoeway/yomitan/blob/69b57e5efdc8a25025606569f8f20ea508a5263d/ext/js/display/display-anki.js#L111-L126
> As far as I can tell `options.anki.enable` is never checked so these events will always trigger even if Anki integration is disabled.
> 

_Originally posted by @01b6 in https://github.com/themoeway/yomitan/issues/825#issuecomment-2067071154_

**Comment by Kuuuube** [comment] 2024-04-20 13:10
Although the exact circumstances are slightly different, the error and issue are a duplicate of #825 and as you mention, it's reported in a comment on that issue as well.

**Closed by Kuuuube** 2024-04-20 13:10 UTC
