### ISSUE TITLE
Play the audio of the searched word! 

### ISSUE THREAD

**Issue by RyanOrigens** [themoeway/yomitan#866] opened 2024-04-28 21:23 UTC
Currently, you can only play the audio of the stem word with Yomitan (the ones shown in the dictionary, rather than the ones you hovered over). On the fork of Yomichan for Spanish by [seth-js](https://github.com/seth-js), there was a feature that allowed you to play the audio of the searched word simply by holding shift while clicking on the icon. It would be nice if this feature were also implemented in Yomitan.

For languages like Spanish, which has billions of verbalizations, it ended up being extremely useful to be able to check the audio of the searched word as well.

**Comment by Kuuuube** [comment] 2024-04-28 21:37
Duplicate of #573

**Closed by Kuuuube** 2024-04-28 21:37 UTC
Labels: kind/enhancement
