### ISSUE TITLE
Allow selection through touch long press.

### ISSUE THREAD

**Issue by Lolle2000la** [themoeway/yomitan#726] opened 2024-02-24 13:53 UTC
Currently, when using Yomitan on touch screen devices like Firefox for Android, normal touch presses/releases are the only way to select a term. However, when using a webpage in Japanese, pressing the various interface elements will lead to unwanted popups opening. To prevent that it would be nice if one could instead use the more intentionally used long press gesture to select terms.  
Alternatively, it would be cool if selecting text will also give the popup, similarly to how it currently pops up for images with alt texts.

**Comment by StefanVukovic99** [comment] 2024-02-24 13:55
related: #681

**Comment by yogurtroyale** [comment] 2024-03-08 08:04
I signed up for github to make this exact post. I would love it if there were a setting for scanning only highlighted text.

**Comment by Kuuuube** [comment] 2024-04-29 17:50
Duplicate of #681

**Closed by Kuuuube** 2024-04-29 17:50 UTC
Labels: kind/enhancement
