### ISSUE TITLE
Yomitan changing whole webpages to light mode

### ISSUE THREAD

**Issue by m-wynn** [themoeway/yomitan#1173] opened 2024-07-03 03:00 UTC
**Description**
1. Go to a site like https://daisyui.com/docs/install/?lang=ja
2. Press `shift` to activate yomitan
3. Notice the whole page turns light mode

DaisyUI does have a Theme Controller which yomitan might be interfering with.
https://daisyui.com/components/theme-controller/

**Browser version**
Firefox 127.0.2

**Yomitan version**
Yomitan 24.6.24.0

**Comment by Kuuuube** [comment] 2024-07-03 03:01
Duplicate of https://github.com/themoeway/yomitan/issues/1166

**Closed by Kuuuube** 2024-07-03 03:01 UTC
Labels: kind/bug
