### ISSUE TITLE
Slow Dictionary Import Feature (Android)

### ISSUE THREAD

**Issue by shiki-tm** [themoeway/yomitan#1458] opened 2024-10-05 01:17 UTC
On my Samsung note phone I cant import Wikipedia and similar large dictionaries (probably those with entries close to 1 million or with a lot of pics). The yomitan settings page crashes and says I ran out of memory. Ive tried some things to clear up memory and restarting my phone and right after that trying to import etc but it always fails. I wonder if its possible to add a feature like jidoujisho has, for slower import of dictionaries. My phone isnt new but it isnt low end, it has like 10-12gb of ram..

Also weird thing I noticed is I have this Chinese names corpus dict that is also 1million entries (somehow got imported) but i want to delete it but cant. The progress bar just stays at 0 percent and then after like a minute or 2 the bar goes away and nothing is deleted.

**Comment by Kuuuube** [comment] 2024-10-05 01:19
Duplicate of #863

To delete that dict you may need to delete all dicts.

**Closed by Kuuuube** 2024-10-05 01:19 UTC
Labels: kind/enhancement

**Comment by MarvNC** [comment] 2024-10-05 01:37
#374 for the failing to delete issue, strange since that was supposed to be fixed.

**Comment by MarvNC** [comment] 2024-10-05 01:37
Also as a workaround you can export your dictionary collection and import that on the phone, it works no matter how large the collection is.
