### ISSUE TITLE
How to add Google text to speech and audio from websites

### ISSUE THREAD

**Issue by YossefGamerr** [themoeway/yomitan#945] opened 2024-05-15 01:43 UTC
I want to add the option to listen to the dutch words using Google translate TTS when I click the sound button next to the word, 
how can I do that? 

and possibly is there a way to add audio from websites like DutchPod101, just like how there is an option for JapanesePod101? is there a way to get the audio from websites like that?

**Comment by StefanVukovic99** [comment] 2024-08-11 19:47
Duplicate of completed #948

**Closed by StefanVukovic99** 2024-08-11 19:47 UTC
Labels: area/audio
