### ISSUE TITLE
Error: Anki not connected

### ISSUE THREAD

**Issue by aramrw** [themoeway/yomitan#919] opened 2024-05-12 05:06 UTC
**Description**
Almost 2000 `Error: Anki not connected` messages in the console.
I've had this happen for a while and I'm not sure if it's actually causing any problems, but if it is I haven't noticed anything other than the error messages. 🤷🏼‍♂️ 

![chrome_5p1vQQhiYQ](https://github.com/themoeway/yomitan/assets/106574385/224a819a-c38e-4bdf-b5d4-fc8696c59c2b)

**Browser version**
`124.0.6367.202`

**Yomitan version**
`Yomitan 24.4.16.0`

**Exported settings file**
[yomitan-settings-2024-05-12-05-03-19.json](https://github.com/themoeway/yomitan/files/15285135/yomitan-settings-2024-05-12-05-03-19.json)

**Comment by jamesmaa** [comment] 2024-05-12 06:11
This is resolved in the latest dev we will push out the fix to stable tomorrow

**Comment by Kuuuube** [comment] 2024-05-13 22:09
Duplicate of #825

**Closed by Kuuuube** 2024-05-13 22:09 UTC
Labels: kind/bug
