### ISSUE TITLE
Rename `{selection-text}` to `{popup-selection-text}`

### ISSUE THREAD

**Issue by jamesmaa** [themoeway/yomitan#1062] opened 2024-06-14 00:17 UTC
Is there some weird backward compatibility issue we would have to deal with? 

Related:
Blocker for #641 (would like `{selection-text}` to reference this)

**Comment by peldas** [comment] 2024-06-14 06:16
This sounds like a bad idea as it's currently worded. There are a lot of people who use `{selection-text}` who don't keep up to date on what's happening with Yomitan and would just think something broke if this change were made.

You instead should:
1. Add a separate handlebar to add the new functionality from #641
2. Create a duplicate of `{selection-text}` called `{popup-selection-text}`
3. Deprecate `{selection-text}` so it can still be used for backwards compatibility but doesn't appear in the dropdown

**Comment by Kuuuube** [comment] 2024-06-14 21:01
We can run a settings update to replace `{selection-text}` with whatever the new one is. And due to how handlebar updates are applied we can make it so even if a user has edited the handlebar it will still be updated to the new name.

But just deprecating it and removing it from dropdown is probably fine too.

**Closed** 2024-07-12 18:06 UTC
Labels: area/tech-debt
