### ISSUE TITLE
Highlight sentence to Anki/multiple card types or decks

### ISSUE THREAD

**Issue by elemn** [themoeway/yomitan#1047] opened 2024-06-10 23:58 UTC
I have an idea for Yomichan which i feel would very much improve sentence mining. As of now, adding a card requires adding the entire sentence. My thought is that it would be really neat to be able to select (highlight) the part of the sentence that one wants, then to be able to hotkey hover over the word, then when adding a card and definition, have the anki card take only the highlighted text to Anki. This would help in adding text that is not properly part of the sentence but useful for context, or taking an excerpt when a sentence is extremely long.

Default behaviour could remain without highlighting.

Another thing I would like to see at some point is the ability to use two different templates, or two different decks. Currently, you can only add according to one note type (with the option to do kanji or kana. I think it would be nice to be able to have 2 buttons buttons where : 

1. Add sentence card 
2. add word card

Optionally, it'd be nice to be able to have these in seperate decks. This could also work through a drop down menu. e.g. 

1. Add sentence card in x deck
2. add word card in x deck
3. add grammar card in x deck

Where presets are configured in settings (with the ability to keep defaults).

Just some ideas. I very much enjoy the addon, so thank you for maintaining it : )

**Comment by jamesmaa** [comment] 2024-06-12 04:46
Could you split your asks into separate issues? It makes it hard to assign this work when the scope is huge.

Adding selected text is a duplicate of #641 
Multiple add buttons is kind of covered in the description in #893

**Comment by elemn** [comment] 2024-07-13 16:43
Closed because of duplicates.

**Closed** 2024-07-13 16:43 UTC
Labels: kind/enhancement, area/anki
