### ISSUE TITLE
Scrolling on Firefox mobile triggers popup despite settings

### ISSUE THREAD

**Issue by pavliuk-ii** [themoeway/yomitan#534] opened 2024-01-16 21:30 UTC
**Description**
I've been using kiwi+yomichan until recently, so I decided to migrate to yomitan and on top of that switch to firefox.
There are two issues I currently have:
1. If you set up scroll prevention inputs that used to work on old yomichan on yomitan, the popup stops showing up at all ([configuration 1](https://github.com/themoeway/yomitan/assets/71011278/58f503b6-ae5e-4906-93bb-217435f31224)) (screenshot taken from https://github.com/KamWithK/AnkiconnectAndroid#instructions)
I've tried changing settings a bit and found a configuration where it seems to work similarly ([configuration 2](https://github.com/themoeway/yomitan/assets/71011278/40951dfc-7d46-4fbb-a751-cf63fcf7121d)), and it works well on kiwi, but here comes the second issue:
2. When I use these settings on firefox, the popup still keeps appearing on scroll, despite "prevent touch scrolling" enabled. I suppose that it's the issue with how scrolling in firefox works, but is there any way to live with that? I can't read anything when once I scroll the screen a bit to advance with the text it throws a popup at me.

**Browser version**
Kiwi Browser 120 / Firefox Mobile 121.1.0

**Yomitan version**
23.12.29.0

**Exported settings file**
Two setting files, one for each input configuration:
[input settings.zip](https://github.com/themoeway/yomitan/files/13955942/input.settings.zip)

**Comment by djahandarie** [comment] 2024-01-20 01:57
Hmm, haven't looked into it yet, but it must be that Firefox Mobile is triggering different events :thinking: I wonder why...

**Comment by Lyroxide** [comment] 2024-02-23 16:15
@djahandarie This issue occurs on Kiwi browser too. With KamWithK's settings on Yomitan 23.12.29.0, a single tap press would not trigger a pop-up, but a long press will (with text selected incorrectly, but the pop-up is correct). Using Yomitan 23.11.23.0, this issue does not occur. Seems like a regression occurred somewhere.

**Comment by praschke** [comment] 2024-03-15 22:40
@pavliuk-ii "prevent touch scrolling" prevents cancelable touch move events from scrolling the view, it's not meant to prevent scanning.

i found a configuration using pointer inputs which improves over the emulated mouse in firefox android (on master).

- tapping scans
- scrolling doesn't scan, because scrolling results in a pointercancel instead of a pointerup
- long taps produce a selection, and if you then scroll, you don't have to dismiss the popup to move the selection anchors
- after interacting with the root popup (eg collapsible dictionaries, nested scanning), pointerup events on the underlying page don't target the root popup's document like emulated mousedown events do, so the root popup doesn't get stuck open or closed. i'm enabling "auto-hide search popup" just in case.
- unfortunately, dragging horizontally on a popup can still scroll the underlying page behind it and kill all popups except the root
- unfortunately, clicking internal links can still scan the initial text of the new search results

![Screenshot_20240315-220500](https://github.com/themoeway/yomitan/assets/91733887/3b044bcc-8433-49dd-9a90-24fa1bce5e00)
![Screenshot_20240315-220405](https://github.com/themoeway/yomitan/assets/91733887/0f4056db-0f54-4a3b-8466-bca36aa81b52)
![Screenshot_20240315-220433](https://github.com/themoeway/yomitan/assets/91733887/59e67c7c-3f0c-4b24-bd06-1d6f246e71d1)

**Comment by Kuuuube** [comment] 2024-04-15 02:19
Fixed in #791 with the new touchtap option.

**Closed** 2024-04-15 17:46 UTC
Labels: kind/bug, browser/firefox
